### ISSUE TITLE
Error when performing batch correction on single H5AD dataset

### ISSUE THREAD

**Issue by PeteHaitch** [jkanche/kana#116]
Mock up an H5AD in R:

``` r
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(zellkonverter))

set.seed(1000)
sce <- mockSCE()
dim(sce)
#> [1] 2000  200
# Will use `Treatment` as a fake batch variable.
table(sce$Treatment)
#> 
#> treat1 treat2 
#>    100    100

writeH5AD(sce, file = "mockSCE.h5ad")
#> ℹ Using the 'counts' assay as the X matrix
```

Loading that into https://www.jkanche.com/kana/, selecting `Treatment` as batch variable, then hitting 'Analyze' yields for me:
<img width="1392" alt="Screen Shot 2022-04-20 at 2 46 53 pm" src="https://user-images.githubusercontent.com/1049741/164152432-e5c2f8a2-ddc7-4761-bf4f-0e37888c76a9.png">

CC: @dunstone-a

**Comment by LTLA** [comment]
Looks like the relevant code doesn't deal with H5AD's factor concept properly. We should probably just coerce it to a string array, these factors have proven to be more trouble that they're worth.

Immediate workaround would be to use string arrays rather than factors, but not sure whether you can save it to H5AD without something converting it into a factor down the line. So the next-best approach is just to integer-ify the relevant variable.

This is also tracked in LTLA/bakana#11.

**Comment by jkanche** [comment]
@PeteHaitch this PR: https://github.com/jkanche/kana/pull/118 along with the changes @LTLA made in bakana should fix this.

for now, if you are running this on the same dataset, change the # of HVGs in the parameters (under PCA) to 100 (since the dataset only contains 200 genes). we'll auto choose this based on the dimensions: https://github.com/LTLA/bakana/issues/13

**Comment by PeteHaitch** [comment]
Thanks for the quick fix!
