### ISSUE TITLE
Gene symbols or ID for cell annotation

### ISSUE THREAD

**Issue by proteinosome** [jkanche/kana#132]
Hi, thanks for this amazing applications that allow us to quickly produce results on a browser. I have a question with regards to the cell annotation using reference. I understand that the software attempts to "guess" whether the first columns of "genes.tsv" file is Ensembl ID or symbol, then use that to infer whether to use symbol or ID from the references. However, the first column may not necessarily be symbol or Ensembl ID. For example, in the case of looking at novel isoforms, the first column can sometimes be used to denote a new isoforms and called "ID.XXX" and this can cause the guessing to be thrown out of the loop.

For example, when I name the first column as "PB.12.10--WASH7P--novel_in_catalog", the result is different from just naming it "WASH7P". I will however need to name it the former since I'm trying to decipher which isoform it is.

In the case of unconventional naming of first columns, is it possible to force the software to use the second column (which is usually symbol/gene names) for cell annotation?

Following this question, is there any other part of the software that users need to be aware of whereby unconventional naming of first columns can cause an issue?

Thank you!

**Comment by LTLA** [comment]
In this case, the guess for Ensembl ID should be poor, given that you don't have any columns that match with the `ENSGxxx` pattern. In contrast, you should (hopefully) have a column that look like human gene symbols. (This is heuristically defined by **scran.js**'s [`guessFeatures`](https://github.com/jkanche/scran.js/blob/master/js/guessFeatures.js)  as starting with upper-case, having no lower-case, and not being an Ensembl ID.)

This should encourage the app to choose the good-symbol-like column for annotation instead of the poor Ensembl-(un)like column, assuming that enough of the entries in the former match the heuristic.

**Comment by proteinosome** [comment]
Thanks Aaron @LTLA ! Doesn't the guess only happens on the first column of "genes.tsv" file? I.e. if I have weird ID in the first column, but correct gene symbols on the second column, it won't work, right? 

If I rename the first columns to gene symbols, there will be duplicates since I'm working at isoforms level (i.e. one gene will have multiple isoforms). How does Kana handle duplicated gene symbols?

Thank you!

**Comment by LTLA** [comment]
> Thanks Aaron @LTLA ! Doesn't the guess only happens on the first column of "genes.tsv" file? I.e. if I have weird ID in the first column, but correct gene symbols on the second column, it won't work, right?

No, both columns are considered when deciding which feature namespace to use. (Well, they should be. If not, it's a bug.)

It's just that, usually, the Ensembl ID gets picked because the application is more confident in the heuristic. `guessFeatures` will output a confidence score for its guesses, and if Ensembl IDs are available, the confidence is usually 100% because every value follows the `ENSG[0-9]{11}` pattern - for human, at least. In contrast, not all gene symbols follow our no-small-caps heuristic, so the confidence is often lower. Thus the symbol column usually doesn't get picked.

In your case, the first column doesn't match anything well, so the second column of gene symbols will have the highest confidence and get selected for use in cell labelling. The reference datasets have both symbols and Ensembl IDs, so the application can switch between them depending on whatever is available.

> If I rename the first columns to gene symbols, there will be duplicates since I'm working at isoforms level (i.e. one gene will have multiple isoforms). How does Kana handle duplicated gene symbols?

I believe that the last of the duplicates gets used. Basically, it's the one with the last say, so it overrides all other duplicates.

**Comment by proteinosome** [comment]
Super clear, thanks for the explanation!
